---
- name: Show Running Config on Cisco switch
  hosts: switches
  gather_facts: no
  connection: network_cli
  vars:
    provider:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      authorize: yes
      auth_pass: "{{ enable_password }}"
      platform: cisco_ios

  tasks:
    - name: Show running-config
      ios_command:
        provider: "{{ provider }}"
        commands:
          - show running-config
      register: output

    - name: Print output
      debug:
        var: output.stdout_lines
