- name: Create VLAN and Interface
  hosts: SW_Core_MA
  gather_facts: no
  vars:
    username: szbidi
    password: Cisco123*
    enable_password: Cisco123*
    vlan_id: "{{ hostvars[inventory_hostname]['vlan_id'] }}"
    vlan_ip: "{{ hostvars[inventory_hostname]['vlan_ip'] }}"
    
  tasks:
    - name: Create VLAN
      ios_vlan:
        vlan_id: "{{ vlan_id }}"
        name: "{{ vlan_name }}"
        state: present
        provider:
          host: "{{ inventory_hostname }}"
          username: "{{ username }}"
          password: "{{ password }}"
          authorize: yes
          auth_pass: "{{ enable_password }}"
          platform: cisco_ios
     - name: Create VLAN interface
       ios_interface:
         name: "Vlan{{ vlan_id }}"
         description: "Interface for VLAN {{ vlan_id }}"
         ipv4:
           address: "{{ vlan_ip }}"
           mask: "255.255.255.0"
         state: present
        provider:
          host: "{{ inventory_hostname }}"
          username: "{{ username }}"
          password: "{{ password }}"
          authorize: yes
          auth_pass: "{{ enable_password }}"
          platform: cisco_ios
        with_items:
          - "{{ vlan_id | string | int }}"
