- name: Create VLAN on Cisco switch
  hosts: switches
  gather_facts: no
  connection: ssh
  vars:
    vlan_id: 100
    vlan_name: management

  tasks:
    - name: Configure VLAN
        cisco.ios.ios_command:
        commands:
          - "vlan {{ vlan_id }}"
          - "name {{ vlan_name }}"
      register: output

    - name: Save configuration
        cisco.ios.ios_command:
        commands:
          - "write memory"
