- name: Create VLAN and Interface
  hosts: SW_Core_MA
  gather_facts: no
  vars:
    username: szbidi
    password: Cisco123*
    enable_password: Cisco123*
    vlan_id: "{{ vlan_id | int }}"
  tasks:
    - name: Create VLAN
      ios_vlan:
        vlan_id: "{{ vlan_id }}"
        name: "VLAN{{ vlan_id }}"
        state: present
        provider:
          host: "{{ inventory_hostname }}"
          username: "{{ username }}"
          password: "{{ password }}"
          authorize: yes
          auth_pass: "{{ enable_password }}"
          platform: cisco_ios
    - name: Create VLAN interface
      ios_interface:
        name: "Vlan{{ vlan_id }}"
        description: "Interface for VLAN {{ vlan_id }}"
        ipv4:
          address: "{{ vlan_ip }}/24"
        state: present
        provider:
          host: "{{ inventory_hostname }}"
          username: "{{ username }}"
          password: "{{ password }}"
          authorize: yes
          auth_pass: "{{ enable_password }}"
          platform: cisco_ios
