---
- name: assign int to vlan
  hosts: SW_Core_TN
  gather_facts: false
  vars: {vlan_id: '100', int_type: E, int_id: 0/0, name: '{{int_type}}{{int_id}}'}
  tasks:
  - name: Add VLAN using aggregate
    ios_vlan:
      aggregate:
      - {vlan_id: '{{ vlan_id }}', interfaces: '{{ name }}'}
