---
- name: Add VLAN to switch
  hosts: SW_Core_MA
  gather_facts: no
  vars:
    username: szbidi
    password: Cisco123*
    enable_password: Cisco123*
    vlan_id: "{{ hostvars[inventory_hostname]['vlan_id'] }}"
    vlan_ip: "{{ hostvars[inventory_hostname]['vlan_ip'] }}"
  tasks:
    - name: Show running-config
      ios_command:
        commands:
          - show running-config
        provider:
          host: "{{ inventory_hostname }}"
          username: "{{ username }}"
          password: "{{ password }}"
          authorize: True
          auth_pass: "{{ enable_password }}"
          platform: cisco_ios
      register: running_config
    - name: Create VLAN
      ios_vlan:
        vlan_id: 100
        name: TEST_VLAN
        state: present
        provider:
          host: "{{ inventory_hostname }}"
          username: "{{ username }}"
          password: "{{ password }}"
          authorize: True
          auth_pass: "{{ enable_password }}"
          platform: cisco_ios
