- name: Create VLAN and Interface
  hosts: SW_Core_MA
  gather_facts: no
  vars:
    username: szbidi
    password: Cisco123*
    enable_password: Cisco123*
  tasks:
    - name: Override device configuration of all interfaces with provided configuration
      cisco.iosxr.iosxr_l3_interfaces:
        config:
        - name: vlan"{{ vlan_id }}"
          ipv4:
          - address: 192.168.0.1/24
