- name: add  vlan on port Trunk
  hosts: SW_Core_TN
  gather_facts: no
  vars: {name: '{{int_type}}{{int_id}}'}
  tasks:
  - name: trunk
    ios_l2_interface:
      config:
      - name: '{{ name }}'
        mode: trunk
        trunk: {allowed_vlans: 'add {{ allowed_vlans }}', encapsulation: dot1q}
        state: merged
  - name: Save running to startup when modified
    cisco.ios.ios_config:
      save_when: modified
