- name: add new vlan interface and give it ip addr
  hosts: SW_Core_MA
  gather_facts: no
  #vars: {ipaddr: 192.168.13.13, subnet: 255.255.255.0, vlan_id: '100', name: 'Vlan{{vlan_id}}'}
  vars: {name: 'Vlan{{vlan_id}}'}
  tasks:
  - name: add "Vlan{{vlan_id}}"
    ios_config:
        lines:
          - int {{ name }}
          - no shutdown
          - ip addr {{ipaddr}} {{subnet}}
   - name: Save running to startup when modified
     cisco.ios.ios_config:
       save_when: modified
