---
- name: configure trunk port
  hosts: SW_Core_TN
  gather_facts: false
  vars: {int_type: g, int_id: 1/1, name: '{{int_type}}{{int_id}}', allowed_vlans: '1,2'}
  tasks:
  - name: trunk
    ios_l2_interfaces:
      name: '{{ name }}'
      mode: trunk
      trunk: {allowed_vlans: '{{ allowed_vlans }}', encapsulation: dot1q}
      state: merged
