- name: Check VLAN 1 status
  hosts: SW_Core_MA SW_Core_TN
  gather_facts: no

  tasks:
    - name: Get VLAN 1 status
      ios_command:
        commands:
          - show vlan id 1
      register: vlan1_output

    - name: Check VLAN 1 status
      assert:
        that:
          - "'active' in vlan1_output.stdout[0]"
        fail_msg: "VLAN 1 is not up you do the Best Practices"
        success_msg: "No Compliance N°01: VLAN 1 is up ===> you must desactivate IT"
        
    - name: Get VTP status
      ios_command:
        commands:
          - show vtp status
      register: vtp_output

    - name: Check VTP mode
      assert:
        that:
          - "'Transparent' in vtp_output.stdout[0]"
        fail_msg: "Not Complance N°02 VTP mode is not set to Transparent"
        success_msg: " VTP mode is set to Transparent"
        
    - name: Get VTY configuration
      ios_command:
        commands:
          - show run | include transport input|output ssh
      register: vty_output

    - name: Check VTY configuration
      assert:
        that:
          - "'transport input ssh' in vty_output.stdout[0]"
          - "'transport output ssh' in vty_output.stdout[0]"
        fail_msg: "Not Compliance N°03 VTY is not configured To SSH transport input&output check your configuration"
        success_msg: "VTY is configured for SSH transport input/output great job "
        
    - name: Get log for mismatch
      ios_command:
        commands:
          - show logging | include mismatch
      register: log_output
      ignore_errors: true

    - name: Display mismatch log
      debug:
        msg: "{{ log_output.stdout_lines }}"
      when: log_output.stdout_lines | length > 0

    - name: Display success message
      debug:
        msg: "Switch is functioning properly"
      when: log_output.stdout_lines is not defined or log_output.stdout_lines | length == 0

