- name: Check Cisco switch compliance with best practices
  hosts: SW_Core_MA
  gather_facts: no

  tasks:
    - name: Check VLAN configuration
      cisco.ios.command:
        commands:
          - show ip interface brief
      register: vlan_output
      
    - debug:
          var: vlan_output
