- name: Assign interface to VLAN
  hosts: cisco_device
  gather_facts: no

  vars:
    interface_name: Ethernet0/0
    vlan_id: 100

  tasks:
    - name: Configure interface
      ios_command:
        commands:
          - interface {{ interface_name }}
          - switchport access vlan {{ vlan_id }}


