---
- name: Configure interface on Cisco IOS device
  hosts: SW_Core_MA
  gather_facts: no

  vars:
    interface_name: Et0/0
    description: "Connected to LAN switch port"

  tasks:
    - name: Configure interface description
      ios_command:
        commands:
          - interface {{ interface_name }}
          - description {{ description }}
        provider:
          host: "{{ inventory_hostname }}"
          username: admin
          password: mysecretpassword



