- name: Assign interface to VLAN
  hosts: SW_Core_MA
  gather_facts: no

  vars:
    vlan_id: 100

  tasks:
    - name: Configure interface
      ios_command:
        commands:
          - interface {{ interface_name }}
          - switchport access vlan {{ vlan_id }}


