---
- name: Assign VLAN to interface
  hosts: SW_Core_MA
  gather_facts: no
  vars:
    vlan_id: 100
    interface_name: Et0/0
  tasks:
    - name: Configure VLAN on switch
      ios_config:
        lines:
          - interface {{ interface_name }}
          - switchport mode access
          - switchport access vlan {{ vlan_id }}
        provider:
          host: "{{ inventory_hostname }}"
          username: admin
          password: mysecretpassword



