- name: Add VLAN to switch
  hosts: SW_Core_MA
  gather_facts: no
  vars:
    username: szbidi
    password: Cisco123*
    enable_password: Cisco123*
  tasks:
    - name: Configure L3 interface
      cisco.ios.ios_l3_interfaces:
        config:
        - name: Ethernet0/0
          ipv4:
          address: 192.168.1.1
          netmask: 255.255.255.0
        state: present
        provider:
          host: "{{ inventory_hostname }}"
          username: "{{ username }}"
          password: "{{ password }}"
          authorize: True
          auth_pass: "{{ enable_password }}"
          platform: cisco_ios
      become: yes
