- name: Configure TACACS on Cisco IOS device
  hosts: SW_Core_MA
  gather_facts: no
  
  vars:
    tacacs_server: 192.0.2.1
    tacacs_key: secretkey
    
  tasks:
    - name: Enable AAA
      ios_config:
        lines:
          - aaa new-model
    
    - name: Configure TACACS server
      ios_config:
        lines:
          - tacacs-server host {{ tacacs_server }}
          - tacacs-server key {{ tacacs_key }}
    
    - name: Configure login authentication
      ios_config:
        lines:
          - aaa authentication login default group tacacs+ local
          
    - name: Configure enable authentication
      ios_config:
        lines:
          - aaa authentication enable default group tacacs+ enable
