- name: Configure VTY lines on Cisco IOS device
  hosts: SW_Core_MA, SW_Core_TN
  gather_facts: no
  vars:
    transport_input: all
    transport_output: all
  tasks:
    - name: Configure VTY lines
      ios_config:
        lines:
          - line vty 0 4
            transport input {{ transport_input }}
            transport output {{ transport_output }}
