- name: Configure Spanning Tree Protocol
  hosts: SW_Core_MA
  gather_facts: no
  vars:
    stp_mode: pvst
    stp_priority: 4096
  tasks:
    - name: Configure STP mode
      ios_config:
        lines:
          - spanning-tree mode {{ stp_mode }}

    - name: Configure STP priority
      ios_config:
        lines:
          - spanning-tree vlan 1-4094 priority {{ stp_priority }}



