- name: Create new user with privilege
  hosts: SW_Core_TN
  gather_facts: no
  tasks:
    - name: Create new user
      ios_config:
        lines:
          - username {{ username }} privilege {{ privilege }} password {{ password }}

