- name: Save configuration on Cisco IOS device
  hosts: SW_Core_MA SW_Core_TN
  gather_facts: no
  tasks:
    - name: Save configuration
      ios_config:
        lines:
          - "do write memory"

